Repository CodeForAfrica/sensors.AFRICA, pull requests merged in 2018-10, with the labels that each got.

#78 Fix footer break in Firefox
  src/components/Footer.js
Labels: bug

#80 Switch to Logo Option 2
  src/assets/Logo-White.png
  src/assets/images/logos/logowhite.png
Labels: bug, enhancement

#81 Fix all links and buttons on the site
  src/assets/images/logos/cfafrica_gray.png
  src/assets/images/logos/cfafrica_white.png
  src/assets/images/logos/innovateafrica_gray.jpg
  src/assets/images/logos/innovateafrica_white.png
  src/components/About/Partners.js
  src/components/About/Stories.js
  src/components/AirComponents/IndoorOutdoor.js
  src/components/CityComponents/CallToAction.js
  src/components/CityComponents/Header/CityMenuBar.js
  src/components/CityComponents/HostSensors/HostCard.js
  src/components/CityComponents/HostSensors/HostSensorButtons.js
  src/components/Footer.js
  src/components/Header/MenuBar.js
  src/components/Header/Navbar.js
  src/components/JoinNetwork/JoinSupport.js
  src/components/Support.js
  src/pages/air/AirHome.js
Labels: bug, enhancement

#85 Hotfix/city+search
  src/components/CityComponents/Header/CityGauge.js
  src/components/CityComponents/Header/CityGaugeContainer.js
  src/components/CityComponents/Header/CityHeader.js
  src/components/CityComponents/Header/CityMenuBar.js
  src/components/CityComponents/Header/CitySearchBar.js
  src/components/Hambuger/MenuButton.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/CityGauge.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/index.js
  src/components/Maps/Kenya.js
  src/components/Maps/Nigeria.js
  src/components/Maps/Tanzania.js
  src/components/SearchBar.js
  src/pages/air/City.js
Labels: bug

#86 [Hotfix] Reduce routing to Pages and not Components
  src/components/AirComponents/AirHeader.js
  src/components/CityComponents/Header/CityHeader.js
  src/components/CityComponents/Header/CityMenuBar.js
  src/components/CityComponents/Header/CitySearchBar.js
  src/components/Header/JumbotronContent/AirHeaderContent.js
  src/components/SearchBar.js
  src/pages/air/City.js
  src/pages/air/index.js
Labels: bug, enhancement

#88 [Hotfix] Switch to `//` for URLs to ensure uniform scheme is used
  src/components/Maps/Kenya.js
  src/components/Maps/Nigeria.js
  src/components/Maps/Tanzania.js
Labels: bug, enhancement

#101 Fix Site Typography
  src/App.js
  src/assets/css/index.css
  src/components/About/Partners.js
  src/components/About/Staff.js
  src/components/About/Stories.js
  src/components/AirComponents/IndoorOutdoor.js
  src/components/AirComponents/Issues.js
  src/components/CityComponents/CallToAction.js
  src/components/CityComponents/HostSensors/ArrowCards.js
  src/components/CityComponents/HostSensors/HostCard.js
  src/components/CityComponents/Neighbourhood.js
  src/components/CityComponents/PollutionStats.js
  src/components/CityComponents/SensorsQualityStats/DataTable.js
  src/components/CityComponents/SensorsQualityStats/QualityStats.js
  src/components/Footer/index.js
  src/components/Hambuger/HambugerMenu.js
  src/components/Header/JumbotronContent/AboutHeaderContent.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/index.js
  src/components/Header/JumbotronContent/AirHeaderContent.js
  src/components/Header/JumbotronContent/HardwareHeaderContent.js
  src/components/Header/JumbotronContent/JoinHeaderContent.js
  src/components/Landing/Hero.js
  src/components/Landing/TestQuality.js
  src/components/Maps/Kenya.js
  src/components/Maps/Nigeria.js
  src/components/Maps/Tanzania.js
  src/components/SensorsInfo/HardwareInfo.js
  src/components/SocialMedia.js
  src/components/Support.js
  src/index.js
  src/pages/air/HowSensorsWork.js
  src/pages/sound/SoundHome.js
  src/pages/water/WaterHome.js
Labels: bug, enhancement

#102 landing page implementation
  src/App.js
  src/assets/css/index.css
  src/components/AirComponents/AirHeader.js
  src/components/CityComponents/Header/CityMenuBar.js
  src/components/CityComponents/Header/CitySearchBar.js
  src/components/Hambuger/MenuButton.js
  src/components/Header/JumbotronContent/AirHeaderContent.js
  src/components/Header/Navbar.js
  src/components/SearchBar.js
  src/components/SocialMedia.js
Labels: bug, enhancement

#106 Add "Scroll to Top" on page change
  src/App.js
  src/ScrollToTop.js
Labels: bug

#107 Improve font and button implementation
  src/App.js
  src/components/About/Stories.js
Labels: bug, enhancement

#108 Add percentage gauge
  src/components/AirComponents/GaugeChart.js
  src/components/AirComponents/Issues.js
Labels: enhancement

#110 [Fix] House Cleaning
  CONTRIBUTING.md
  README.md
  package.json
  src/assets/Logo-White.png
  src/components/CityComponents/Header/CityMenuBar.js
  src/components/Header/MenuBar.js
  src/withRoot.js
  yarn.lock
Labels: bug, enhancement

#105 Fix footer images
  src/assets/css/App.css
  src/components/Footer/Email.js
  src/components/Footer/index.js
Labels: bug

#103 Fix support section design
  src/App.js
  src/components/Support.js
Labels: bug

#115 [Hotfix] Fix Select Dropdown and Warnings
  src/ScrollToTop.js
  src/components/AirComponents/IndoorOutdoor.js
  src/components/AirComponents/Issues.js
  src/components/CityComponents/Header/CityHeader.js
  src/components/CityComponents/HostSensors/ArrowCards.js
  src/components/CityComponents/SensorsQualityStats/DataTable.js
  src/components/Header/Navbar.js
  src/components/SearchBar.js
Labels: bug

#116 Update Project Setup
  .gitignore
  package.json
  yarn.lock
Labels: enhancement

#112 Minor improvements on the footer design
  src/App.js
  src/assets/css/App.css
  src/assets/css/index.css
  src/components/Footer/Email.js
  src/components/Footer/index.js
  src/components/SocialMedia.js
Labels: bug, enhancement

#113 Improve homepage design
  src/App.js
  src/assets/css/App.css
  src/assets/css/index.css
  src/assets/images/background/bglanding.jpg
  src/components/Landing/Hero.js
  src/components/Landing/TestQuality.js
Labels: bug, enhancement

#121 Improve staff design component
  src/components/About/Staff.js
Labels: bug, enhancement

#122 Fix partner image section
  src/App.js
  src/assets/css/index.css
  src/assets/images/logos/innovateafrica_gray.jpg
  src/components/About/Partners.js
Labels: bug, enhancement

#125 Improve how sensors work hardware component
  src/components/SensorsInfo/HardwareInfo.js
  src/pages/air/HowSensorsWork.js
Labels: bug, enhancement

#136 [Hotfix] Fix api url http/https scheme issue
  src/components/Api.js
  src/pages/air/City.js
Labels: bug, enhancement

#137 Update general site UI to match design
  src/assets/css/App.css
  src/components/AirComponents/IndoorOutdoor.js
  src/components/CityComponents/CallToAction.js
  src/components/Footer/Email.js
  src/components/Footer/index.js
  src/components/Support.js
  src/pages/air/City.js
Labels: bug, enhancement

#139 Fix city page redesign
  src/components/CityComponents/Header/CityHeader.js
  src/components/Maps/Kenya.js
  src/pages/air/City.js
Labels: bug, enhancement

#123 Fix typography for all header components
  src/components/About/AboutHeader.js
  src/components/CityComponents/Header/CityHeader.js
  src/components/Header/JumbotronContent/AboutHeaderContent.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/CityGauge.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/index.js
  src/components/Header/JumbotronContent/HardwareHeaderContent.js
  src/components/Header/JumbotronContent/JoinHeaderContent.js
  src/components/SensorsInfo/HardwareHeader.js
Labels: bug, enhancement

#140 Improve hamburger burger design
  src/components/Hambuger/HambugerMenu.js
  src/components/Hambuger/MenuButton.js
  src/components/Header/MenuBar.js
Labels: bug, enhancement

#135 Improve quality statistic component
  src/components/CityComponents/SensorsQualityStats/DataTable.js
  src/components/CityComponents/SensorsQualityStats/QualityStats.js
Labels: bug, enhancement

#141 [WIP] [#161471102] Update About contents
  src/components/About/AboutHeader.js
  src/components/About/Partners.js
  src/components/AirComponents/IndoorOutdoor.js
  src/components/AirComponents/Issues.js
  src/components/CityComponents/PollutionStats.js
  src/components/Footer/index.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/CityGauge.js
  src/components/Header/MenuBar.js
  src/components/JoinNetwork/JoinHeader.js
  src/components/SensorsInfo/HardwareHeader.js
  src/components/SensorsInfo/HardwareInfo.js
Labels: enhancement

#142 Improve the host sensor component design
  src/assets/css/App.css
  src/components/CityComponents/HostSensors/ArrowCards.js
  src/components/CityComponents/HostSensors/HostCard.js
  src/components/CityComponents/HostSensors/HostSensorButtons.js
  src/components/CityComponents/HostSensors/index.js
Labels: bug, enhancement

#143 [Chore] Fixes small but necessary UI, code and dependency issues
  package.json
  src/components/CityComponents/Header/CityHeader.js
  src/components/Footer/index.js
  src/components/Header/JumbotronContent/AboutHeaderContent.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/CityGauge.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/index.js
  src/components/Header/Navbar.js
  src/components/Maps/Kenya.js
  src/components/Maps/Nigeria.js
  src/components/Maps/Tanzania.js
  src/index.js
  src/pages/air/City.js
  yarn.lock
Labels: bug, enhancement

#144 [#161375673] Coming Soon Popup
  package.json
  src/App.js
  src/assets/css/App.css
  src/components/ComingSoon.js
  src/components/Email.js
  src/components/Footer/index.js
  src/components/Header/Navbar.js
  src/components/Landing/TestQuality.js
  src/pages/air/City.js
  src/pages/air/JoinNetwork.js
  yarn.lock
Labels: enhancement
