Repository CodeForAfrica/sensors.AFRICA, pull requests merged in 2019-02, with the labels that each got.

#190 Improve 404 Page [163317945]
  src/pages/NotFound.js
Labels: bug, enhancement

#193 Cleanup repo before v0.3 release [164052724]
  package.json
  src/components/Email.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/CityGauge.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/RadialGauge.js
  src/components/Header/JumbotronContent/HardwareHeaderContent.js
  src/components/Header/JumbotronContent/JoinHeaderContent.js
  src/components/HealthClimate/Burden.js
  src/components/SearchBar.js
  src/stories/index.js
  yarn.lock
Labels: bug

#191 Introduce EXPLORE button [161672328]
  package.json
  src/components/City/HostSensors/HostSensorButton.js
  src/components/City/HostSensors/HostSensorButtons.js
  src/components/City/HostSensors/ShareButton/SocialMediaButtons.js
  src/components/City/HostSensors/ShareButton/index.js
  src/pages/air/City.js
  yarn.lock
Labels: bug, enhancement

#192 Automatic pull stories for Showcase from gSheet [163085196]
  package.json
  src/components/Showcase/Stories.js
  src/components/Showcase/StoryList.js
  yarn.lock
Labels: enhancement

#189 Add partners logo component
  src/assets/images/partners/data4sdg.jpg
  src/assets/images/partners/liquidtelcom.png
  src/assets/images/partners/partnershipsdg.png
  src/assets/images/partners/worldbankgroup.png
  src/components/PartnerLogos.js
  src/pages/air/About.js
  src/pages/air/City.js
  src/pages/air/Data.js
  src/pages/air/HealthAndClimateImpacts.js
  src/pages/air/HowSensorsWork.js
  src/pages/air/JoinNetwork.js
  src/pages/air/index.js
Labels: enhancement

#196 Update archive link in the data page
  src/components/DataArchives/DataArchives.js
Labels: bug, enhancement

#198 Pre Site Launch Review
  src/assets/css/App.css
  src/components/City/Header/CityHeader.js
  src/components/City/SensorsQualityStats/DataTable.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/CityGauge.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/DigitalGauge.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/RadialGauge.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/index.js
  src/components/Logo.js
  src/components/SearchBar.js
  src/components/SocialMedia.js
  src/pages/air/City.js
Labels: bug, enhancement

#194 City page line graph
  package.json
  src/components/City/QualityStatsGraph.js
  src/components/City/SensorsQualityStats/DataTable.js
  src/components/City/SensorsQualityStats/StatsSummary.js
  src/components/City/SensorsQualityStats/index.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/RadialGauge.js
  src/pages/air/City.js
  yarn.lock
Labels: bug, enhancement
