Repository CodeForAfrica/sensors.AFRICA, pull requests merged in 2019-01, with the labels that each got.

#179 Add back button to the coming soon alert popup
  src/components/ComingSoon.js
  src/components/Header/Navbar.js
  src/components/Landing/TestQuality.js
Labels: enhancement

#176 Add share button to the host sensors component [161644078]
  src/components/City/HostSensors/HostSensorButton.js
  src/components/City/HostSensors/HostSensorButtons.js
  src/components/City/HostSensors/ShareButton/Embed.js
  src/components/City/HostSensors/ShareButton/SocialMediaButtons.js
  src/components/City/HostSensors/ShareButton/index.js
Labels: enhancement

#181 Add city name to url [162036430]
  src/App.js
  src/components/DocumentHead/PageHeads.js
  src/components/SearchBar.js
  src/pages/air/City.js
  src/pages/air/index.js
Labels: enhancement

#183 Move showcase component to below the hero section of the city home page
  src/components/Air/Issues.js
  src/components/Showcase/index.js
  src/pages/air/index.js
Labels: bug

#184 Update indoor outdoor component
  src/components/Air/IndoorOutdoor.js
Labels: bug

#180 Improve mobile responsiveness [161644164]
  src/assets/images/button/airbtn.png
  src/assets/images/button/soundbtn.png
  src/assets/images/button/waterbtn.png
  src/components/About/Partners.js
  src/components/About/Staff.js
  src/components/City/CallToAction.js
  src/components/City/Header/CityHeader.js
  src/components/City/HostSensors/HostSensorButton.js
  src/components/City/PollutionStats.js
  src/components/City/SensorsQualityStats/DataTable.js
  src/components/City/SensorsQualityStats/index.js
  src/components/Hambuger/HambugerMenu.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/CityGauge.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/DigitalGauge.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/RadialGauge.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/index.js
  src/components/Header/JumbotronContent/AirHeaderContent.js
  src/components/Header/MenuBar.js
  src/components/Header/Navbar.js
  src/components/SearchBar.js
  src/pages/air/City.js
Labels: bug, enhancement

#185 Add data page with details of how to use sensors.AFRICA API
  src/App.js
  src/components/DataArchives/DataArchives.js
  src/components/DataArchives/DataArchivesHeader.js
  src/components/DocumentHead/PageHeads.js
  src/components/Hambuger/HambugerMenu.js
  src/components/Header/JumbotronContent/DataArchivesHeaderContent.js
  src/pages/air/Data.js
  src/pages/air/index.js
Labels: enhancement

#186 Fix content layout on the data page
  src/components/DataArchives/DataArchives.js
Labels: bug, enhancement

#187 Allow users to submit form on keypress enter
  .prettierrc.json
  src/components/Email.js
Labels: enhancement
