Repository CodeForAfrica/sensors.AFRICA, pull requests merged in 2019-03, with the labels that each got.

#200 [Fix] Data table mobile view
  src/components/City/SensorsQualityStats/DataTable.js
  src/components/City/SensorsQualityStats/index.js
  src/components/PartnerLogos.js
Labels: bug, enhancement

#201 [Fix] Mobile view chart labels
  src/components/City/QualityStatsGraph.js
Labels: bug, enhancement

#197 Fix dial component in the city page
  package.json
  src/components/City/Header/CityHeader.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/NeedlePointer.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/RadialGauge.js
  yarn.lock
Labels: bug

#202 sensors.AFRICA embeds
  .env
  src/App.js
  src/api/index.js
  src/components/City/HostSensors/ShareButton/Embed.js
  src/components/City/HostSensors/ShareButton/index.js
  src/components/Embeds/AirGauge.js
  src/components/Embeds/AirGraph.js
  src/components/Embeds/AirMap.js
  src/components/Embeds/index.js
  src/components/Header/JumbotronContent/AirCityHeaderContent/RadialGauge.js
  src/pages/air/City.js
Labels: enhancement

#204 Add sensors.AFRICA about us page content
  src/components/About/AboutContent/Content.js
  src/components/About/AboutContent/index.js
  src/pages/About.js
  src/pages/air/About.js
Labels: enhancement
