Repository CodeForAfrica/sensors.AFRICA, pull requests merged in 2020-03, with the labels that each got.

#236 Add Logo to Partners Section
  src/assets/images/partners/germanCoopLogo.bmp
  src/components/PartnerLogos.js
Labels: enhancement

#235 Add radiation card
  src/assets/images/button/radiationbtn.png
  src/components/Header/Navbar.js
  src/components/Landing/Hero.js
  src/components/Landing/TestQuality.js
  yarn.lock
Labels: enhancement

#233 Style gauge chart to show outer green stroke line
  src/components/Air/GaugeChart.js
  src/components/Air/HealthEffects.js
Labels: bug, enhancement

#238 [Hotfix] react-helmet
  package.json
  yarn.lock
Labels: bug

#239 [Fix] Analytics + SSR Embeds
  .babelrc
  .gitignore
  README.md
  jsconfig.json
  src/components/Embeds/AirGauge.js
  src/components/Embeds/AirGraph.js
  src/components/Embeds/AirMap.js
  src/lib/gtag.js
  src/pages/_app.js
  src/pages/_document.js
  src/pages/embeded/air/dial.js
  src/pages/embeded/air/graph.js
  src/pages/embeded/air/map.js
  yarn.lock
Labels: bug, enhancement
