Repository CodeForAfrica/sensors.AFRICA, pull requests merged in 2023-09, with the labels that each got.

#316 Added alicia's profile
  src/assets/images/team/Alicia.jpg
  src/components/About/Staff.js
Labels: enhancement

#317 Fix eslint prettier integration
  .eslintrc
  package.json
  src/api/index.js
  src/components/Header/JumboContent/AirCityHeaderContent/RadialGauge.js
  src/components/Showcase/StoryList.js
  src/pages/air/city/[id].js
  yarn.lock
Labels: bug, dependencies

#319 Upgrade Nextjs
  .github/workflows/main.yml
  next.config.js
  package.json
  src/components/Link/NextComposed.js
  yarn.lock
Labels: dependencies, chore
